DELETE FROM reply;
DELETE FROM review;
DELETE FROM ceo;
DELETE FROM market;
DELETE FROM cust;
DELETE FROM categori;
DELETE FROM food;
alter table ceo modify regdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
alter table cust modify regdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
